services:
  backend:
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
  frontend:
    env_file:
      - ./frontend/.env
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    env_file:
      - ./backend/.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: