name: CD

on:
  push:
    branches: ["deployment", "main"]

env:
  REGISTRY: ghcr.io

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/rei-x/swb-backend:latest
          cache-from: type=registry,ref=ghcr.io/rei-x/swb-backend:latest
          cache-to: type=inline
          network: host
          target: backend

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/rei-x/swb-frontend:latest
          cache-from: type=registry,ref=ghcr.io/rei-x/swb-frontend:latest
          cache-to: type=inline
          network: host
          target: frontend

      - name: Trigger build
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
